import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import '../styles/globals.css'
import LeftNavigation from '@/components/LeftNavigation'
import { cn } from '@/lib/utils'

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
  })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
				<main className="App">
					<div className='flex flex-row'>
						{/* Left side page navigation */}
						<LeftNavigation />
						{/* Right side contents */}
						<div className='ml-12  md:ml-44 lg:ml-52'>
							{children}
						</div>
					</div>
				</main>
			</body>
		</html>
	)
}
